--Explore all objects in the Database
select * from INFORMATION_SCHEMA.tables

--Explore all columns in the Database
select * from INFORMATION_SCHEMA.COLUMNS

--Explore all countries our customers come from
select distinct country from gold.dim_customers

--Explore all categories "The major Divisions"
select distinct category, subcategory,product_name from gold.dim_products
order by 1,2,3

--Find the date of the first and last order
--How many years of sales are available
select MAX(order_date) as last_order_date, MIN(order_date) as first_order_date,
DATEDIFF(year, MIN(order_date),max(order_date)) as order_range_years
from gold.fact_sales

--Find the youngest and oldest customer
select DATEDIFF(year, max(birthdate),getdate()) as youngest_customer_age,
DATEDIFF(year, min(birthdate),getdate()) as oldest_customer_age
from gold.dim_customers

--Find the total sales
select SUM(sales_amount) as total_sales from gold.fact_sales

--Find how many items are sold
select SUM(quantity) as total_items_sold from gold.fact_sales

--Find the average selling price
select AVG(price) as average_selling_price from gold.fact_sales

--Find the total number of orders
select COUNT(distinct order_number) as total_orders from gold.fact_sales

--Find total number of products
select COUNT(distinct product_name) as total_products from gold.dim_products

--Find the total number of customers
select COUNT(distinct customer_id) as total_customers from gold.dim_customers

--Find the total number of customers that have placed an order
select COUNT(distinct customer_key)
from gold.fact_sales fs 

--Find total number of customers by countries

select country, COUNT(distinct customer_id)
from gold.dim_customers
group by country

--Find total customers by gender
select gender,COUNT(distinct customer_id)
from gold.dim_customers
group by gender

--Find total products by category
select category, COUNT(distinct product_id)
from gold.dim_products
group by category 

--What's average cost in each category?
select category, AVG(cost)
from gold.dim_products
group by category

--Total revenue generated by each customer
select dc.customer_key, dc.first_name, dc.last_name, SUM(fs.sales_amount)
from  gold.fact_sales fs left join gold.dim_customers dc
on dc.customer_key = fs.customer_key
group by dc.customer_key,dc.first_name, dc.last_name
order by SUM(fs.sales_amount) desc

--Total revenue by each category
select dp.category, sum(fs.sales_amount)
from gold.fact_sales fs left join gold.dim_products dp
on fs.product_key = dp.product_key
group by dp.category

--Distribution of sold items across countries?
select dc.country,SUM(fs.sales_amount)
from  gold.fact_sales fs left join gold.dim_customers dc
on dc.customer_key = fs.customer_key
group by dc.country
